trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
- group: trexo  # ✅ This links the variable group named "trexo"

- name: droplet_host
  value: '209.38.124.176'

- name: droplet_user
  value: 'root'

- name: project_dir
  value: '/root/Trexo-backend'

steps:
- task: UseNode@1
  inputs:
    version: '18.x'

- script: |
    echo "Setting up SSH..."
    mkdir -p ~/.ssh
    echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ssh-keyscan -H $droplet_host >> ~/.ssh/known_hosts
  displayName: 'Configure SSH Key'
  env:
    SSH_PRIVATE_KEY: $(ssh-private-key)

- script: |
    echo "Deploying to droplet..."
    ssh $droplet_user@$droplet_host << EOF
      cd $project_dir
      git pull origin main
      npm install
      pm2 restart trexo-backend || pm2 start npm --name trexo-backend -- run dev
    EOF
  displayName: 'SSH and Deploy'