trigger:
  branches:
    include:
      - main

variables:
  ssh_host: "root@209.38.124.176"
  project_dir: "/root/Trexo-backend"

stages:
- stage: DeployToDroplet
  displayName: "Deploy to DigitalOcean Droplet"
  jobs:
  - job: SSHDeploy
    displayName: "SSH into Droplet and Deploy"
    pool:
      vmImage: "ubuntu-latest"

    steps:
    - script: |
        echo "Setting up SSH key..."
        cat <<EOF > do_key
        -----BEGIN RSA PRIVATE KEY-----
        MIIJKAIBAAKCAgEA0YbmTlJqW/0cPAFn6GJf+Y5EAv/5Ylk2cBkl+Sg59636UvB7
        TXsrS07KshLN3guX+o3vJfrRrIvBid47cje7f9dqJ4g42kUg7+IphG65sZk9Rgrk
        R1ccFg5dOnbB73s4UIlu5E0fjUQGd7Q8AajB6MqP0rUrngIvrula4tWTcZgThsyi
        /KDTWa3hc9ztiQ3ozQE4H9wJ5/oZgU8uhUVKTh3+01kopWxmJqQ7lg8czmEpSZMP
        6e8o4Nh6iAdCgnP6TWyaW8H0JHqnzH/GobcNJ/e/srwWwSvafIqUYlUzODzkmIWI
        z2+NWyxfzT8okjdgA82w0HbPptwVNQHOsVVMaenOIAEhjne7wPo6e95j64js004D
        EShkle1xxoJufoQMujypGanFT371ygZe7OUB/Tol9GC9wq5yzUMIxsRNCkScxdMU
        cDWUYAKrQyBOuO1LbkW22ltRrWKaKzJdLNJsmQPuDCKmx5PmDZJSkIHsIaXp5eki
        g6GwHbjXAXaLamPVFeEt5vlZV2pI4oKgJdfoU84VcU80r7ST6T4AKHlkJ4m9YZgP
        +eXccIMoc+tY1UkwNOtba2OYeUYwUBcA39fgwZuoHjiaW3eBoEoqc2xQWWQ1YR27
        iVWaiE0WgyUGOAQK+K1IBy53mla81crSJGkKsZRQkpNKY8eyfGxNuNTwnXcCAwEA
        AQKCAgAFCm0eqUDsdvRnmn5jdX/AQznuUIuGtYVnwP3MNrmI9I3h0kNFI+zGDQk3
        Vi3PD7xXnMk0wrSp+rAXSa9ob2AlZ+CilCu5+eZxnvacvFqJ+UPOHD5NsRIjPbPk
        ei2Zk1Sm1geYRSVjLVByhMraHLM9jydSobqA51CPsVwsZN2n4p66+XqvqowrINHH
        CyOeeSUxTrwzmARCU8lVS7sKHcFMi9Aw9CN+3KgVzzxXvy6pkGYr4kvZtuqRg45p
        w12dlyizFXpz3ACsTVRyyQgq+npojGn3j4AvTtzHbkC6SjkckJUh+ORyXnP/eNvS
        gO3QRrYaoVIwUbYWhOjwXjDDd2ff1pmwtTGyNEv54Gqzy5VQflWJRxYDcdpkJ0o0
        j0QbpnXw4cfa8AHAFoRfPIyZD3ZhWXdYlirCIHPwTiWnQ5p7VXssQAd8B74M9+1C
        UHFqmyRy1suMvtijoYb8l9H2E3x9rVs46rpz2EvG4hQ0Y4dwdFg40z5OcWC6hT+5
        94Z5SPmlRAcvVkDLneLzH89ZPZELKGvf4jl7A9YgwLbYul9QVPUYC/BpgRs8KsJB
        DIUFXY0Tuuw2iTsNZEcI1SXvbLbkFtisparXoxRqHRXsKLnMU052rgLicvvy2eVF
        Z99bgNztlBg9Sv0iIDZ35fJIR92zR0MaL/DEZJC7S6tdD/8tUQKCAQEA9bSDOqMB
        AXIjbxF88Sku7sgjhsoIiaX9a/bpV0qelwKqXSqYUeoqGK72f7mDvjzBKPVhu0Q2
        3j9VsQDpnraf9UswsXqBlR1UMQB2jYr5MoUGgqN6bXWC0zNbR5OtiKY7Ik30MqrG
        9uP8vskYvI9D+2tRwzFW26PVz9hV92kDZ6NO81Zs+Ab8Kw+JBcRrebgbv6vlGRgp
        gkF8N96bNWTLSjDspnvzXuiVmrocl66Mn4Mz0/sEcOHn7xjxGfDmDcMWEhOubdp3
        D687xFdeYtKOePr3+8pJd9t6RWv+QCQdDrcnIJpixqJgJ34sUjWBSNDM88Wd70jL
        f7c0wS+uu4hJzQKCAQEA2k5U+TIe8d/U5r/2p1beNxgVwKBuEUtr9eTAkcGn3uzx
        SOngS/IUJSWG2NTG/YL3CBeq+O4UHSccvR55dyMyyTqR57ux6yQfhfeBf92OtkYj
        QeA/0wHCE5O248T3vyD+3eg/q+Rri9vFnolkVH2qt7LjQQlBm6RhyM5NqUdKY74G
        FsshqPjb1wAILjILnqgJfU3lR/eFAi8K0SfrrI4869wtxF2PbWUW4HXzEwgK+naQ
        u5gFE5QLcQA+KRoOyrbQmZWZ87/J5etP0iGuv5EbKmxsFhssgvjibrIZ+oQ/8UCW
        Y8qI7am/imYnSwLkX6kzKkb1cg72kBtX1xDuYlNwUwKCAQEA6BxiCAeq0InZrXgQ
        1uV3370TyqabECXN1KtJXdwxGyk6dY7inCehIvZOCPTg3tsYArBkZfsX9jZQpkjd
        acDONXSViGPZfFtbiHsOg8IwjagbMVhsNHFZaFlQtrpsqfWXUV3g/ehU0zEnN7hT
        dPXGXAHTGJlIm28XciTFeVcsD0C4OaqAgIJgv/EKGXenrDHfjN8/KsinldR1G3Zg
        mz0fynOTa+cWTqdbhPKiRixvzdStJmkwlc7jQv0F7uKjAYc1F1ieZEqIRTneNSnw
        EV0lmGZF1AgSBXdB98kAQ+mZxagB/4u5GjqUqVpJVlQTUQ1nQDaEb2MOUxVoccOw
        xpoGVQKCAQA6FHUPB4KsHzzpV1EsHDRqvAGtigE+oK5McVu6a6dZ6/gVygNesT0i
        1OUXcySt9dX7VTCrocvAJdPDjQQL6lVsrCR9XrZrNOUeI0dU2YFKhUaEFEFmxiT4
        SGh0GMdBFmo4Z73o4ZCrWQEuuKb0w6pTzUgg2XGXExjg7+JBkzH7b2b3UXvXFL6I
        aP3ELJRi1ZoQuFSz3OqKNjHOi6xr8DvNFHsoryulkyuO9FKDUbR6BmljP4K6Prz8
        h3ACR2iADjtZYS/gZbo1bXGDGmr/lH+Bve7Tws8I2WaExOWcfOr2KJTaX9wmPu8y
        xxLVJiPUP5PZP5+1hL2cgWnRUjPZ/RD5AoIBACVU0AzyglnwS1gD5sSG4NiClPOt
        o5XnVT0sygTJ8O1LD14Lf3pMoLTQHedyO2iSHhj12wPvJ0LASPERBUvPMSAWVxGK
        Cl8bNDgmbBbA/5cpoDuBXjNMmb26Zk9JpX+YJPN6NB2Ga5ATOCWHg5zjRyOwun8Y
        lrOWgL/UcwDcnWdJ+exGdM8b4UAgz1HsuQCcqvTIap/VYPsQDI7d5AYh7deJwkxv
        DpEqpvp2ldVc25rCnUCEJ3oGtA2wV9aksmuPb74qwJ6BWo9X7zrc/LpeSlLKK6TO
        ZLJ1PrpyPbbViT8U6qPE0kFLGBJZxH89SzzdQIfeo2tBo9U1YRVi6KLLNI8=
        -----END RSA PRIVATE KEY-----
        EOF
        chmod 600 do_key

        echo "Connecting to Droplet and deploying..."
        ssh -i do_key -o StrictHostKeyChecking=no $(ssh_host) << EOF
          cd $project_dir
          git fetch
          git pull origin main
          npm install
          pm2 restart all
        EOF
      displayName: "SSH Deploy Script"
